version: '3.8'

services:
  soft-skills-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soft-skills-practice-service
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - POINTS_QUEUE_NAME=${POINTS_QUEUE_NAME}
      - ACHIEVEMENTS_QUEUE_NAME=${ACHIEVEMENTS_QUEUE_NAME}
      - PROFILE_QUEUE_NAME=${PROFILE_QUEUE_NAME}
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
    restart: unless-stopped
    volumes:
      - ./src:/app/src  # Para desarrollo con hot-reload
    networks:
      - soft-skills-network

networks:
  soft-skills-network:
    driver: bridge