version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: soft-skills-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: soft_skills_practice
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d/
    networks:
      - soft-skills-network

  redis:
    image: redis:7.2-alpine
    container_name: soft-skills-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ""
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - soft-skills-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: soft-skills-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      HTTP_USER: admin
      HTTP_PASSWORD: redis123
    depends_on:
      - redis
    networks:
      - soft-skills-network


  mongo-express:
    image: mongo-express:1.0.0
    container_name: soft-skills-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - soft-skills-network

volumes:
  mongodb_data:
  redis_data:

networks:
  soft-skills-network:
    driver: bridge